# Generated by Django 4.2.7 on 2023-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('to_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('text_body', models.TextField()),
                ('sender_provider', models.CharField(max_length=100)),
            ],
        ),
    ]
