version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c " 
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    stdin_open: true
    tty: true
